### PR TITLE
fix: check label list list column type earlier

### LINKED ISSUE #2844: bug: entered unreachable code: Should verify that the first column is a list earlier
Should not return IO error. 

```
entered unreachable code: Should verify that the first column is a list earlier
```

### PR DESCRIPTION
**Pull request by LuQQiu**
fixes #2844

### CODE REVIEW

**Comment by LuQQiu** [comment]
make: *** [test] Illegal instruction: 4
python/tests/test_filter.py::test_duckdb

**Comment by LuQQiu** [comment]
rust linux-arm Error: The operation was canceled.

**Comment by LuQQiu** [comment]
@westonpace @wjones127 PTAL, thanks!

**Comment by LuQQiu** [comment]
New version: (0, 17, 1)
  File "/home/runner/work/lance/lance/pr/../base/ci/check_versions.py", line 64, in <module>
    new_version[1] == last_version[1] + 1
AssertionError: Minor version should have been bumped because there was a breaking change.
Last version: (0, 17, 0)

**Review by westonpace — APPROVED** [review]
Thanks for cleaning this up!

**Comment by LuQQiu** [comment]
> Thanks for cleaning this up!

Thanks for reviewing and providing good suggestions!

**Pull request merged**
