### PR TITLE
feat: add integer conversion for index and search

### PR DESCRIPTION
**Pull request by triandco**
This pull request is motivated by https://github.com/lancedb/lancedb/issues/678

The current lancedb only supports floating types for searchable vectors in the database. However, storing large vectors in as float is not feasible for devices with little storage. For these cases, we might want to use integer or boolean vectors instead. This pull request introduces a conversion step so that integer vector can be search for with the same precision as existing float vectors. Once it is merged, we can relax the float check in lancedb to address the mentioned use case. 

I wonder if this has any pitfalls with lance's current approach or if I missed any related bits, so I open it as a draft. If this approach is reasonable, I can extend it to boolean types which would give us even better compression so that lance can run on more storage restrictive environments.

Please let me know your thoughts.

### CODE REVIEW

**Review by wjones127 — COMMENTED** [review]
It would definitely be great to support integer vectors.

I think we could pursue implementing in the order you are proposing here, but would need to see a lot more tests.

It might also make sense to instead start by implementing proper distance function kernels. I think just a PR with distance functions for integer vectors would be a good first contribution. The other thing that would need to be specialized is the encodings. We use PQ encoding for vector indices, which compresses the floats. But we probably would want to skip that step for integers. I think most of the other logic would work the same between floats and integers.

**Comment by wjones127** [comment]
It looks like we've started some work on u8 vectors here:  #2501

**Comment by triandco** [comment]
Thank @wjones127. I think starting with the distance function is a good idea. It'll be more efficient as well.
Look like work is already well on the way. I'll close this PR in favor of that approach.

**Comment by triandco** [comment]
@wjones127, I don't see support for integer type vector on [2024 roadmap](https://github.com/lancedb/lance/issues/2079), but I can see recent PR being done toward this goal. Is this something that the team is actively working towards or the PR were just side effect of your current plan? 

For my work, I would very much appreciate support for u8/i8/i16/bool etc. I'm happy to contribute a few PR, but I don't want to double up the work if they are all coming soon.

**Comment by BubbleCal** [comment]
Hi @triandco, we have a plan to support binary vectors and hamming distance in the future, they will come in 2~4 weeks.

For the other integer vector types, we don't have recent plans

**Comment by miretchin** [comment]
Is binary vectors / hamming in yet?

**Pull request closed without merging**
