### PR TITLE
perf: exclude sign bit if all values are negative

### LINKED ISSUE #2714: Exclude sign bit from bitpacked encoding if all values are negative
In https://github.com/lancedb/lance/pull/2662 we added support for bitpacking signed integers in LanceV2. In https://github.com/lancedb/lance/pull/2696, an optimization was made to exclude the sign bit if all the values for a signed type are positive. 

We can make a further optimization to exclude the sign bit if all the values are negative.

The way to do this could be to:
- change the Bitpacked encoding proto message to have a flag indicating all the values are negative
https://github.com/lancedb/lance/blob/35e38624b91a17c5202f38bb587d8b432914dd58/protos/encodings.proto#L176
- In `bitpack_params_for_signed_type` add logic to determine if all values are negative, and if so, don't add the sign bit to the number of bits. We can also modify the return type `BitpackParams` as suggested [here](https://github.com/lancedb/lance/pull/2696#pullrequestreview-2228412590):
https://github.com/lancedb/lance/blob/b9990d935b0c68ca7149ed8efe45d2f4ee3d9249/rust/lance-encoding/src/encodings/physical/bitpack.rs#L79
- In the decoder, if all the bits are negative then determine this from the field on the encoding proto-message instead of checking the MSB of the encoded value like we do here:
https://github.com/lancedb/lance/blob/b9990d935b0c68ca7149ed8efe45d2f4ee3d9249/rust/lance-encoding/src/encodings/physical/bitpack.rs#L440-L445

### PR DESCRIPTION
**Pull request by gagan-bhullar-tech**
PR fixes #2714

### CODE REVIEW

**Review by wjones127 — CHANGES_REQUESTED** [review]
Thanks for making this PR!

I don't see a test checking that values correctly roundtrip with this code path. Could you add a test for negative values similar to this one for positive values?

https://github.com/lancedb/lance/blob/3751059da800c05621e04bb3b3e4cd2fbd6f00b4/rust/lance-encoding/src/encodings/physical/value.rs#L730-L738

**Comment by gagan-bhullar-tech** [comment]
> Thanks for making this PR!
> 
> I don't see a test checking that values correctly roundtrip with this code path. Could you add a test for negative values similar to this one for positive values?
> 
> https://github.com/lancedb/lance/blob/3751059da800c05621e04bb3b3e4cd2fbd6f00b4/rust/lance-encoding/src/encodings/physical/value.rs#L730-L738

@wjones127 added test. Please review.

**Comment by wjones127** [comment]
@gagan-bhullar-tech It appears the test is showing that the negative values are coming back positive: https://github.com/lancedb/lance/actions/runs/10581352235/job/29321570568?pr=2780#step:11:1214

Let me know when this is fixed and I should re-review.

**Comment by wjones127** [comment]
@gagan-bhullar-tech The test is still failing with:

```
Mismatch at index 0 expected PrimitiveArray<Int32>
[
  -4,
  -4,
  -4,
  -5,
  -4,
  -5,
  -2,
  -2,
  -4,
  -5,
  ...80 elements...,
  -3,
  -2,
  -4,
  -3,
  -2,
  -2,
  -4,
  -5,
  -3,
  -3,
] but got PrimitiveArray<Int32>
[
  4,
  4,
  4,
  3,
  4,
  3,
  6,
  6,
  4,
  3,
  ...80 elements...,
  5,
  6,
  4,
  5,
  6,
  6,
  4,
  3,
  5,
  5,
] first mismatch is expected PrimitiveArray<Int32>
[
  -4,
] but got PrimitiveArray<Int32>
[
  4,
]
```

Are you still working on this?

**Comment by wjones127** [comment]
> @wjones127 I need help figuring this out. Can you please point me in the right direction.

The sign bit tells you whether the numbers were positive or negative. If you drop that bit, it's ambiguous what sign they are. This was fine before, because if `signed = false`, we assumed it was always positive. But now `signed = false` can also mean all-negative. So we need some variable to be saved to represent this.

I would add a field to the `Bitpacked` message: `bool all_negative = 5`. Use `all_negative` since missing fields get default values, and default for `bool` is false. Defaulting `all_negative = false` will match existing behavior.

https://github.com/lancedb/lance/blob/f4e330041c053daeaabe32164ee1896fc6fae8a5/protos/encodings.proto#L176-L188

Then you need to make sure we write this field and read it correctly.

**Comment by gagan-bhullar-tech** [comment]
> > @wjones127 I need help figuring this out. Can you please point me in the right direction.
> 
> The sign bit tells you whether the numbers were positive or negative. If you drop that bit, it's ambiguous what sign they are. This was fine before, because if `signed = false`, we assumed it was always positive. But now `signed = false` can also mean all-negative. So we need some variable to be saved to represent this.
> 
> I would add a field to the `Bitpacked` message: `bool all_negative = 5`. Use `all_negative` since missing fields get default values, and default for `bool` is false. Defaulting `all_negative = false` will match existing behavior.
> 
> https://github.com/lancedb/lance/blob/f4e330041c053daeaabe32164ee1896fc6fae8a5/protos/encodings.proto#L176-L188
> 
> Then you need to make sure we write this field and read it correctly.

Thanks. I will try this next week. Closing this PR for now. Will raise another PR if I am able to fix this.

**Pull request closed without merging**
