### PR TITLE
feat: add replace_schema_metadata and replace_field_metadata

### PR DESCRIPTION
**Pull request by westonpace**

### CODE REVIEW

**Comment by westonpace** [comment]
I've chosen to modify the existing `UpdateConfig` instead of adding a new operation but we could also add a new operation if we think that's better.

**Comment by wjones127** [comment]
> I've chosen to modify the existing `UpdateConfig` instead of adding a new operation but we could also add a new operation if we think that's better.

FWIW, I plan on completely refactoring transactions work at some point in the near future. https://github.com/lancedb/lance/pull/3204

**Review by wjones127 — APPROVED** [review]
looks good!

**Comment by westonpace** [comment]
> FWIW, I plan on completely refactoring transactions work at some point in the near future. https://github.com/lancedb/lance/pull/3204

I'll take a look (and try and sneak this in :) )

**Pull request merged**
