### PR TITLE
chore(java): enable lance-jni rust release

### PR DESCRIPTION
**Pull request by LuQQiu**
Enable the release of lance-jni so that it's utils can be reused by lancedb-jni rust module

### CODE REVIEW

**Comment by wjones127** [comment]
Our release process is documented here: https://github.com/lancedb/lance/blob/main/release_process.md

Not sure if this is the appropriate PR, but could we make sure to document the java release as part of that. Also consider whether you want java releases to also do beta/preview ones, or just full ones.

**Comment by LuQQiu** [comment]
@wjones127 We are figuring out the java release process, probably do manual release for the first one, and then add it to the automatic action later

**Comment by LuQQiu** [comment]
@QianZhu could we enable lance-jni rust release?
this is only for lancedb-jni rust to reuse the same JNI functions

**Comment by QianZhu** [comment]
> @QianZhu could we enable lance-jni rust release? this is only for lancedb-jni rust to reuse the same JNI functions

Do we have to consider the compatibility between the versions of lance-jni and lancedb-jni?

**Review by QianZhu — APPROVED** [review]

**Comment by LuQQiu** [comment]
@QianZhu 
LanceDB spark catalog service depends on Lance Spark connector
LanceDB lancedb jni depends on lance jni

Ideally it better to be the same version dependencies as LanceDB vs Lance Rust core

**Pull request merged**
