### PR TITLE
JNI example in Scala

### PR DESCRIPTION
**Pull request by Renkai**
related issue: https://github.com/eto-ai/lance/issues/646

This is an example of writing dataset to lance in Scala, with a little expand development it can be easy to use in Apache Spark.
And we can add more functions in the JNI class so that other JVM languages (Kotlin/Groovy/Clojure, etc) can use it.

### CODE REVIEW

**Comment by eddyxu** [comment]
thanks for contributing @Renkai .  Is this an example? or it is intended to be THE java/scala SDK?

If it is meant for the official SDK. Let's organize the interface in a way that aligned with Arrow Java SDK and Lance Python/Rust SDK, including naming conversions, method signatures and such. 

As mentioned in https://github.com/eto-ai/lance/issues/646#issuecomment-1447309637 , should we wrap a Java based interface to mimic the python first? Then wrap a scala-style interface for scala?

To have a `Java` core SDK would be help for lance to be used in flink, pinot, kafka and other not-scala-major-projects?

**Comment by Renkai** [comment]
I want the Scala part be an example, and the java part be the lance SDK.

But there are some reasons we can't just mimic the python code.
* Python have PyO3 to communicate with Rust, it looks like a advanced and feature rich library compare to JNI, [jni](https://docs.rs/jni/0.21.0/jni/) seems much rawer.
* Many Python libraries are just thin wrappers of native(C.*/Rust), while Java libraries may want to do many things in Java, because Java is more powerful than Python as well as JNI is more inconvenient than PyO3.

In my current vision, two method is enough for the core Java library, people have other needs can just then use the Arrow Java library:
* `ArrowReader readFromLance(Path path, Query ..)`
* `writeToLance(Path path, ArrowArray array)`

In the example we have the writer. For the reader I have tried locally, it's also not hard to read a full lance file by JNI. 
The missing part is the query, or filter, prediction, whatever. The query should have a common format across languages, or the query should be simple enough so that reimplement it in every language will not be too pain, which path should we choose?

**Comment by eddyxu** [comment]
> In my current vision, two method is enough for the core Java library, people have other needs can just then use the Arrow Java library:

This is fine for a toy personal project. However, It is difficult for me to see how  we can just offer such a raw experience SDK  to users and call it a day. 

Please read https://arrow.apache.org/docs/java/index.html first and make a plan about what kind of interface / structure we need have to have a native Java / JVM experience in the Apache Arrow ecosystem.

**Comment by eddyxu** [comment]
Gonna close it since no activilities.

**Pull request closed without merging**
