### PR TITLE
feat: add encoders/decoders for basic types

### PR DESCRIPTION
**Pull request by westonpace**
This adds encoders and decoders for non-nullable versions of all the arrow types

Prerequisites:

 - [x] https://github.com/lancedb/lance/pull/2137
 - [x] https://github.com/lancedb/lance/pull/2139
 - [x] https://github.com/lancedb/lance/pull/2141

### CODE REVIEW

**Comment by mkleinbort** [comment]
Hey, just checking in. What's your thinking on supporting nullable types? 

At least in our case an empty value (e.g. `[]` or `{'name':null, 'surname':null}` is very different from actually null values. 

Is the plan to support nullable types in v2?

**Comment by westonpace** [comment]
@mkleinbort thanks for checking in.

> Is the plan to support nullable types in v2?

Yes, but I haven't written it down anywhere other than my head.  So let me briefly describe it now.

The proposed format makes it very easy to add new encodings (I would like these to eventually be plugins that can be configured at runtime).

This PR adds "simple struct" which has no validity bitmap and always has one page per file (this is a sort of "dummy column" that has no data and just indicates we are encoding structs without any nulls.

I will shortly add support for "dense validity structs".  This stores the validity bitmap of the struct as a boolean column.  This is easy to implement and will get us nullability support for now.  However, it's pretty rotten for point-lookups.  Loading a single cell requires the I/O for that cell plus and extra IOP to check if the cell is null at the struct level.  If we have a deeply nested value (e.g. struct->struct->struct->primitive) then we pay an extra IOP per level of nesting!

We can optimize this in many cases where there are not many nulls (or not many valid values).  We could store the validity bitmap as a roaring bitmap or even a list of invalid offsets.  In these cases, if the validity bitmap is sufficiently small (e.g. < 4KiB) then we can place it in the column metadata and we will recover our good point lookup performance.

Lastly, we can investigate sentinel encodings.  Sentinel encodings for primitive values are pretty straightforward (find an unused value, use that).  When we have nested values we have to find X unused values.  For example (just an example, we probably won't use the end of the range if we don't have to because that defeats bit packing):

0xFFFFFFFF - Value is null
0xFFFFFFFE - Parent is null
0xFFFFFFFD - Grandparent is null
...

This should allow us to recover point lookup performance, even if there are many nulls, as long as the underlying column has some free bits.  This is actually very similar to parquet's definition levels, the only difference is that we are packing the definition levels with the primitive value itself.

This means we only need to pay the cost of point lookups if:
 * Nulls are frequent but not too frequent
 * The underlying column is very densely populated

I expect this should be fairly rare and we will get "free" nulls in the large majority of cases.

**Comment by westonpace** [comment]
CC @wjones127 as this may be interesting to him as well and I don't think we discussed this in this level of detail before.

**Comment by westonpace** [comment]
Interpreting https://github.com/lancedb/lance/pull/2153#pullrequestreview-1981111627 as transitive approval.  Will merge on green.

**Pull request merged**
