### PR TITLE
feat: expose compression-level configuration for general compression

### PR DESCRIPTION
**Pull request by niyue**
This PR aims to address https://github.com/lancedb/lance/issues/3033, and expose the compression level for general compression.

### CODE REVIEW

**Comment by niyue** [comment]
I check zstd/lz4/snappy [1][2][3], and all of them have the concept of compression level, and all of them use an integer to express such compression level.

[1] zstd compression level, http://facebook.github.io/zstd/zstd_manual.html#Chapter1
[2] lz4 compression level, https://github.com/lz4/lz4/blob/e3974e5a1476190afdd8b44e67106cfb7097a1d5/doc/lz4_manual.html#L144
[3] snappy compression level, https://github.com/google/snappy/blob/32ded457c0b1fe78ceb8397632c416568d6714a0/snappy.h#L54-L72

**Review by wjones127 — APPROVED** [review]
Seems reasonable.

**Comment by wjones127** [comment]
@niyue Could you fix the clippy lints from the Java CI? These do originate from your rust code.

**Comment by niyue** [comment]
Sure. I updated the code to fix the clippy lint issue and two more unit tests. Please check them out. Thanks.

**Comment by broccoliSpicy** [comment]
some lint errors, should be fixable with `cargo fmt --all`

**Comment by niyue** [comment]
> some lint errors, should be fixable with `cargo fmt --all`

Thanks, fixed.

**Pull request merged**
