### PR TITLE
feat: extend python bindings for the v2 reader/writer

### PR DESCRIPTION
**Pull request by ankitvij-db**
PR extends Python Bindings for V2 Writer/Reader and adds bindings for adding global buffers and adding schema metadata both of which are public functions.

### CODE REVIEW

**Review by zhidongqu-db — APPROVED** [review]

**Review by westonpace — APPROVED** [review]
Thanks!  This looks good (pending CI)

**Comment by ankitvij-db** [comment]
@westonpace How does I re-run a failed CI job? I think I did lint before the merge so not sure why the python linter failed.

**Comment by westonpace** [comment]
> How do I re-run a failed CI job?

CI should automatically run anytime you push a commit.  If you need to run a CI job again, without making any changes, the easiest thing to do is usually to rebase main (assuming there is some change).  If there are no changes on main, then you can create an empty commit and push that.

> I think I did lint before the commit so not sure why the python linter failed.

How did you run the lint?  Via IDE?  `make lint`? pre-commit?

I want to make sure our docs are up to date on this.  The easiest thing to do is to use `pre-commit`.  We use `ruff` for linting which is great, but, unfortunately, it seems to change its rules very frequently so its important to match the exact version used in the CI.

**Comment by ankitvij-db** [comment]
> How did you run the lint? 
I did pre-commit

**Comment by ankitvij-db** [comment]
@westonpace How does the python wheel gets released?

**Pull request merged**
