### PR TITLE
feat: enable fp16kernels in Mac and x86 Linux Python wheels

### PR DESCRIPTION
**Pull request by wjones127**
Adds a special x86_64 2_28 build so we can use GCC 12 to build the fp16kernels. We keep around 2_17 for older machines. Doing this for aarch64 will be much harder, so that's left for later.

MacOS always has recent compilers, so enabled trivially here.

MSVC doesn't support fp16, so Windows isn't added.

### CODE REVIEW

**Comment by wjones127** [comment]
I tried to use newer manylinux2_28 so we can use GCC 12 (which supports fp16), however, manylinux cross doesn't support the newer compiler: https://github.com/rust-cross/manylinux-cross/issues/30

It doesn't even support C17.

**Comment by wjones127** [comment]
I think we just have to move away from cross compilation, if we want to ship these kernels. This is unfortunate.

**Review by westonpace — APPROVED** [review]
Cool!  Though...I suppose we need a similar PR for lancedb too now that lancedb is built with maturin.

**Comment by wjones127** [comment]
> Cool! Though...I suppose we need a similar PR for lancedb too now that lancedb is built with maturin.

Yeah, I can do that soon. Hopefully changes should be very similar.

**Pull request merged**
