### PR TITLE
perf: use datafusion to shuffle index partition data

### LINKED ISSUE #1483: Use datafusion kernel to do IVF partition shuffling
Most of the time, `num_partitions` >> `num_rows_per_partition`. For example, you might have 10,000 partitions each with 256 rows. Thus it's not practical to buffer the partition data in memory.

Instead, we can do the partitioning by performing a disk-spilling sort. This kind of sort is already supported by DataFusion, so we can implement it with the query plan:

1. Projection: assign partition id, replace vector column with PQ codes. (see: [transform.rs](https://github.com/lancedb/lance/blob/main/rust/lance-index/src/vector/pq/transform.rs), [residual.rs](https://github.com/lancedb/lance/blob/main/rust/lance-index/src/vector/residual.rs))
2. Sort: sort by partition id, making sure to set a memory limit so we spill to disk
3. Group By: group by partition id (we'll likely do the group by ourselves, since I don't think DF can optimize grouping sorted data)
4. For each group, write partition to index.

### PR DESCRIPTION
**Pull request by wjones127**
This removes the current `Shuffler` in favor of using DataFusion to sort the index data into partitions. DataFusion supports spilling to disk while sorting larger-than-memory data, but will keep the data in memory if it can fit. In theory this can achieve good performance when we need to shuffle the data.

To keep this to a small refactor, I've only replaced the shuffler. However, we could expand the role of DataFusion further by having the partition ID assignment and PQ transformations written in terms of DataFusion's DataFrame API.

Closes #1483

### CODE REVIEW

**Comment by wjones127** [comment]
I did a basic benchmark with (5 million 1536-dimensional 32-bit vectors), and I got basically the same time for building IVF partitions. Both took roughly 16 minutes.

It seemed like the entire time we were CPU bound. I saw all 32 cores on my machine going full blast for the whole IVF partition assignment. Seems like GPU-accelerated assignment or some other efficiency improvement is called for here.

**Comment by wjones127** [comment]
@eddyxu @chebbyChefNEQ  do you have a more representative benchmark? In my test I saw assigning partitions takes 16 minutes and shuffling takes 5 seconds. So it's unclear why we thought optimizing this part would help all that much.

**Comment by wjones127** [comment]
Lei says try again with 65k partitions.

**Review by chebbyChefNEQ — APPROVED** [review]
I think we should start testing index correctness. I'll create a ticket

**Comment by wjones127** [comment]
Okay reran on my example with 4K rows per partition (1,280 partitions) and I saw more than 2x performance increase. `main` took 130s to shuffle while this branch took 60s.

**Pull request merged**
