### PR TITLE
fix: don't panic when v2 scans end early (reader is dropped)

### PR DESCRIPTION
**Pull request by westonpace**
If the reader is dropped during a scan then the scheduler thread is ended after the decoder thread and the io thread.  This means the scheduler thread might get an error sending to a closed receiver.  Previously we would panic on these errors.  With this change we simply log a debug message and end early.

### CODE REVIEW

**Review by yah01 — APPROVED** [review]

**Review by wjones127 — APPROVED** [review]
Seems reasonable. Though surprised there is no unit test as I expect this should be testable?

**Comment by westonpace** [comment]
> Seems reasonable. Though surprised there is no unit test as I expect this should be testable?

The panic was on the scheduler thread which is fire and forget.  So it just logged a message to console there was no other indication (e.g. it did not panic parent thread)

So I wasn't sure how to test it.  I did have a unit test I used for manual testing but wasn't sure about checking in something with no asserts.

**Comment by westonpace** [comment]
@wjones127 I've added some unit tests.  I also now check the scheduler thread when the decode stream drops and propagate any panic that occurred on the scheduler thread.

**Review by wjones127 — APPROVED** [review]
Nice work adding a test

**Comment by wjones127** [comment]
Actually, is the CI failure relevant?

**Comment by westonpace** [comment]
> Actually, is the CI failure relevant?

Hmm, looks like it.  I'll investigate

**Comment by westonpace** [comment]
> Actually, is the CI failure relevant?

Yep.  When the user requested an empty range (e.g. `10..10` the scheduler would panic, this would cause the sending side of the scheduler->decoder link to drop, which made the decoder think the scheduler was done, and an empty batch would be returned)

This is all "technically correct" I guess but we can handle it better.

I was a bit torn on whether the reader should return an error (attempt to read an empty range) or an empty batch.  I went with returning an error (better to advise the user they are doing something fishy) but I could be convinced otherwise (more convenient to tolerate empty ranges).  @wjones127 any particular opinion?

**Pull request merged**
