### PR TITLE
chore: instrument various steps in the ann search

### PR DESCRIPTION
**Pull request by westonpace**

### CODE REVIEW

**Review by eddyxu — APPROVED** [review]

**Review by wjones127 — COMMENTED** [review]
Should we give these a `level`?

**Comment by westonpace** [comment]
@wjones127 

> Should we give these a level?

I don't think we've had any consistent leveling scheme so far.  Maybe:

 * Per operation - info
 * Per batch - debug
 
 ?

**Comment by wjones127** [comment]
Yeah I'm not sure what it should be. TBH I mostly default to `debug` for these traces. Considering whether they are O(batches) seems reasonable.

**Comment by westonpace** [comment]
> Yeah I'm not sure what it should be. TBH I mostly default to debug for these traces. Considering whether they are O(batches) seems reasonable.

@wjones127 

I actually ended up doing something slightly different.  I made everything debug except the top-level "dataset" operations.

**Review by wjones127 — APPROVED** [review]

**Pull request merged**
