### PR TITLE
feat: simple in memory hnsw implementation

### PR DESCRIPTION
**Pull request by eddyxu**
In memory HNSW implementation.

### CODE REVIEW

**Comment by eddyxu** [comment]
Example output from 

`cargo run --example hnsw -r`

```
level=4, ef=50, recall=0.9
level=4, ef=100, recall=0.7
level=4, ef=200, recall=0.8
level=4, ef=400, recall=0.9
level=8, ef=50, recall=0.9
level=8, ef=100, recall=0.8
level=8, ef=200, recall=0.9
level=8, ef=400, recall=0.7
level=16, ef=50, recall=0.9
level=16, ef=100, recall=0.8
level=16, ef=200, recall=1
level=16, ef=400, recall=1
level=32, ef=50, recall=0.9
level=32, ef=100, recall=0.9
level=32, ef=200, recall=0.9
level=32, ef=400, recall=0.8
```

**Review by chebbyChefNEQ — APPROVED** [review]
Can we add a gew E2E smoke tests

**Comment by eddyxu** [comment]
>Can we add a gew E2E smoke tests
There is one as in `examples/hnsw.rs`. Anothing else you'd like to cover

**Comment by chebbyChefNEQ** [comment]
> > Can we add a gew E2E smoke tests
> > There is one as in `examples/hnsw.rs`. Anothing else you'd like to cover

Oh I think we should have one that runs in CI. Otherwise we can't catch breakage in CI

**Pull request merged**
