### PR TITLE
feat: reconnect block compression

### PR DESCRIPTION
**Pull request by westonpace**
This allows block compression (zstd) in the narrow case of using it for binary data.  A more generalized approach to block compression can be handled as part of 2.1.

### CODE REVIEW

**Comment by westonpace** [comment]
> We should probably expose the compression level.

@wjones127 ah, now we run into the question of how we should allow this kind of advanced configuration

We could use a separate metadata key `lance-encoding:compression-level` or we could set the `lance-encoding:compression` key to a non-trivial value (e.g. `{ "lance-encoding:compression": "zstd-3" }`).  (or there are probably a lot of other things we can do).

In general, I don't like exposing too much configuration to the user (which seems hypocritical to say since I think I've added half a dozen environment variables in the last month) without good reason.  Why would a user choose something other than the default compression level?

**Comment by niyue** [comment]
> We should probably expose the compression level

> We could use a separate metadata key lance-encoding:compression-level or we could set the lance-encoding:compression key to a non-trivial value (e.g. { "lance-encoding:compression": "zstd-3" })

> Why would a user choose something other than the default compression level?

@wjones127 @westonpace 
I would like to know whether exposing the compression level as a configurable option is still something being considered. If this is considered, I would be happy to submit a PR for it.

Zstd offers 22 compression levels, each yielding different compression ratios. The compressed data size can vary by up to 50% between levels 1 and 22, depending on data distribution (e.g., [1]). Some databases, like AWS Athena, allow users to specify the Zstd compression level via DDL [2]. Similarly, it would be beneficial if Lance provided the ability to customize compression settings, enabling users to balance time and space efficiency based on their use cases. Thanks.

[1] https://www.reddit.com/r/compression/comments/18e524n/zstd_compression_ratios_by_level/
[2] https://docs.aws.amazon.com/athena/latest/ug/compression-support-zstd-levels.html

**Comment by wjones127** [comment]
I'm for it, if we can find a sensible place to put it.

**Comment by westonpace** [comment]
I'm ok with exposing it.  I'd prefer a entry in the field metadata like `lance-encoding:compression-level`.

**Pull request merged**
