### PR TITLE
chore: sort pq data by row_id inside pq partition(draft, wip)

### PR DESCRIPTION
**Pull request by broccoliSpicy**
This PR tries to sort the pq partitioned data by row_id during `write_pq_partitions`. so during index loading, inside every pq partition, the row_ids are already sorted.

#2612 

I will try to get familiar with the lance python interface and write some test cases in `python/python/tests`

### CODE REVIEW

**Comment by broccoliSpicy** [comment]
This PR tries to sorting the row_id inside one pq_partition during writing, so we can omit the sorting row_id phase when reading, which incurs backward compatibility issues with old versions of dataset, because the old version pq_partition dataset is not sorted by row_id.

I am still trying to figure out how to deal with this.

**Comment by broccoliSpicy** [comment]
> This PR tries to sorting the row_id inside one pq_partition during writing, so we can omit the sorting row_id phase when reading, which incurs backward compatibility issues with old versions of dataset, because the old version pq_partition dataset is not sorted by row_id.
> 
> I can do a check to see if row_id is sorted during reading, but it takes O(n) time, I am still trying to figure out a better way how to deal with this.

I am not sure about lance's backward compatibility support policy, any suggestions here? @westonpace @wjones127

**Comment by westonpace** [comment]
Sorry for the delay in getting to this.  We do need to worry about backwards compatibility.  Old indices will be around for quite some time and must be readable.

That being said:

> This PR tries to sorting the row_id inside one pq_partition during writing, so we can omit the sorting row_id phase when reading, which incurs backward compatibility issues with old versions of dataset, because the old version pq_partition dataset is not sorted by row_id.

I'm not sure if this will work because we might have gaps in the row id sequence due to deleted rows.  An interesting alternative solution could be to introduce an encoding that works well with "mostly" sequential columns.  Then storing the row id should be fairly cheap.

> I will try to get familiar with the lance python interface and write some test cases in python/python/tests

We've been trying to break the steps apart in `indices.py`.  This PR might make it easier to test or at least shows some ways to create quick cheap indices for testing:

https://github.com/lancedb/lance/pull/2670

**Comment by broccoliSpicy** [comment]
> An interesting alternative solution could be to introduce an encoding that works well with "mostly" sequential columns. Then storing the row id should be fairly cheap.

This sounds like a very good approach, I will look into this.

**Comment by westonpace** [comment]
> This sounds like a very good approach, I will look into this.

No rush, maybe just leave the row id in for now and we can optimize storage later.

**Comment by broccoliSpicy** [comment]
> > This sounds like a very good approach, I will look into this.
> 
> No rush, maybe just leave the row id in for now and we can optimize storage later.

sure

**Pull request closed without merging**
