### PR TITLE
feat: switch to using datafusion to parse functions

### LINKED ISSUE #1115: Support array_contains in filter
We support `column IN (<literal values>)` but don't support `array_contains(list_column, <literal_value>)`, even though this is quite useful.

To support this, we'll need to add new logic to handle parsing SQL into DataFusion logical expression:

https://github.com/lancedb/lance/blob/dacfda0cfaab62dc83871488ead90053f17d8c25/rust/src/io/exec/planner.rs#L295

And then add logic to handle translating the logical expressions into physical ones here:

https://github.com/lancedb/lance/blob/dacfda0cfaab62dc83871488ead90053f17d8c25/rust/src/io/exec/planner.rs#L368

See changes here for blueprint: https://github.com/lancedb/lance/pull/983/files

### LINKED ISSUE #1784: Allow datafusion to handle function parsing in expressions
datafusion supports a wide array of functions but the lance parsers explicitly intercepts the parsing and limit function parsing to two recognized functions: https://github.com/lancedb/lance/blob/main/rust/lance/src/io/exec/planner.rs#L201

specific use case here is `array_has_any`

cc @eddyxu do you remember why we explicitly limited this to two functions?

### PR DESCRIPTION
**Pull request by westonpace**
My original plan was to use DF for parsing expressions (not just functions).  However, I ran into some issues:

 * https://github.com/apache/arrow-datafusion/issues/7249
 * Datafusion does not support nested nested references (e.g. it supports `x.y` but not `x.y.z`)
 * Array literals always appear as `List` and not `FixedSizeList`
   * Datafusion's array literals initially show up as "MakeArray" calls and so they are missed by our type coercion.  They turn into literals later during expression simplification.
 * Functions from duckdb (e.g. is_valid) are not recognized by datafusion
   * Long term this kind of engine-to-engine conversion is best handled by substrait
   * In the short term we could maybe register these functions as DF UDFs

So this PR only uses DF to parse the functions.  In addition, we keep the legacy path to handle the `is_valid` function for DuckDb.

Closes #1115 
Closes #1784

### CODE REVIEW

**Comment by westonpace** [comment]
Closes #1784

**Comment by westonpace** [comment]
I've updated #1129 with the incompatibilities I observed this time.

**Comment by wjones127** [comment]
> Datafusion does not support nested nested references (e.g. it supports x.y but not x.y.z)

What do you mean? can't you just nest [GetIndexedField](https://docs.rs/datafusion/latest/datafusion/prelude/enum.Expr.html#variant.GetIndexedField) calls?

**Comment by wjones127** [comment]
Does this fix https://github.com/lancedb/lance/issues/1115?

**Comment by westonpace** [comment]
> Does this fix #1115?

Looks like it.  I've added a regression test for `array_contains`

**Comment by wjones127** [comment]
(Sorry just merged a PR that added some conflicts. Should be easy to resolve though.)

**Pull request merged**
