### PR TITLE
fix: make sure we can append with dictionary columns

### PR DESCRIPTION
**Pull request by wjones127**

### CODE REVIEW

**Comment by dnsco** [comment]
We're failing differently than we were last night with this patch applied. Last night we were getting the same content of the struct but with no offset or length in the second batch,  but now the second batch's dictionary is empty. Not sure if this is a completely different code path being executed or if this is a red herring, but thought I'd throw it out there just in case.

```
[timelord-core/src/running/running_1up_builder.rs:167] (old, new) = (
    Field {
        name: "state",
        id: 28,
        parent_id: 8,
        logical_type: LogicalType(
            "dict:string:int32:false",
        ),
        extension_name: "",
        encoding: Some(
            Dictionary,
        ),
        nullable: true,
        children: [],
        dictionary: Some(
            Dictionary {
                offset: 26,
                length: 3,
                values: Some(
                    StringArray
                    [
                      "DISCONNECTED",
                      "CONNECTED",
                      "FAULT",
                    ],
                ),
            },
        ),
    },
    Field {
        name: "state",
        id: 28,
        parent_id: 8,
        logical_type: LogicalType(
            "dict:string:int32:false",
        ),
        extension_name: "",
        encoding: Some(
            Dictionary,
        ),
        nullable: true,
        children: [],
        dictionary: Some(
            Dictionary {
                offset: 0,
                length: 0,
                values: Some(
                    StringArray
                    [
                    ],
                ),
            },
        ),
    },
    ```

**Comment by wjones127** [comment]
@dnsco is that column all nulls perhaps? trying to understand why the dictionary is empty.

**Comment by dnsco** [comment]
It is very likely that the values are all nulls. The schema is generated from protobufs the actual protobuf mirrors this open source version where there is a container type that has inner variants here https://github.com/dnsco/katniss/blob/0a0be347f508e279e7a826051b44d2eddf5e5974/protos/test/spacecorp.proto#L10

it fails on the first dictionary containing child variant of the oneOf (none of the open source ones have a Dictionary in them, but I could probably reproduce this issue there if I added one, will try).

I'm only currently trying to record one of the inner variants in my company's repo, and it's failing on a schema that I'm not trying to.

Not sure how values could be related though because this is a schemamismatch error, but tl;dr all nulls in that deeply-nested column are very likely.

**Comment by dnsco** [comment]
upon closer inspection the source of the dictionaries are protobuf enums.

**Comment by wjones127** [comment]
First, I found that we don't support null values at all for dictionary arrays. I changed that in the latest commit.

But otherwise, I think you'll need to ensure the dictionary is always consistent when writing a dictionary column. Is that something you'll be able to do?

**Comment by dnsco** [comment]
I'm attempting to reproduce this issue in katniss the open source library but it only exists in our closed source version so Idk wat is going on :'(

Will see if the null stuff fixes it for us

**Review by eddyxu — APPROVED** [review]

**Pull request merged**
