### PR TITLE
chore: update the CI build to check/build all crates in the workspace and not just the lance crate

### PR DESCRIPTION
**Pull request by westonpace**

### CODE REVIEW

**Comment by wjones127** [comment]
@westonpace do you want to add `--benches` to the clippy job too?

**Comment by westonpace** [comment]
> @westonpace do you want to add --benches to the clippy job too?

@wjones127 

Good idea, added

**Review by wjones127 — APPROVED** [review]
Thank you!

**Comment by westonpace** [comment]
The failure seems unrelated.  I opened #1559 and will go ahead and merge this.

**Pull request merged**
