### PR TITLE
ci(java/scala): make spotless maven plugin auto-format in validate phase

### PR DESCRIPTION
**Pull request by yanghua**

### CODE REVIEW

**Review by wjones127 — APPROVED** [review]

**Comment by chenkovsky** [comment]
@yanghua @wjones127 LineLength in checkstyle.xml is 100. but it's 120 in spotless. So when splotless auto-formats code. it may violate checkstyle. maybe we should remove or modify checkstyle.xml if spotlesss is adopted.

**Comment by yanghua** [comment]
> @yanghua @wjones127 LineLength in checkstyle.xml is 100. but it's 120 in spotless. So when splotless auto-formats code. it may violate checkstyle. maybe we should remove or modify checkstyle.xml if spotlesss is adopted.

Hi @chenkovsky thanks for your suggestion.

Actually, I thought about your idea when I introduced the spotless plugin. But I did not try to remove the checkstyle rules. Reasons:

* spotless: is an efficiency tool used to give the whole codebase a unified code style and provide auto-formatting ability.
* checkstyle plugin: has some overlap ability about code style constraint with spotless, while it has some advantage features, for example, `MethodTypeParameterName`, `RegexpSinglelineJava` to detect some forbidden behavior like [this](https://github.com/lancedb/lance/blob/main/java/dev/checkstyle.xml#L179), it is not easy to realize this.
* Currently, the rules of the two tools have few conflicts;

Back to your suggestion:

Based on the default setting, the spotless's rule is broader than the checkstyle plugin. That means if a line length is larger than 120, spotless will format it. If the length is less than 120, then the checkstyle plugin will report it, and let the user format it manually, right?

It looks reasonable, let checkstyle define more binding and serious rules. 

So let's keep watch if there are more conflicts or if we have more reasons to remove one of them.

WDYT?

**Comment by chenkovsky** [comment]
For example, a line contains 119 chars. I split it into multiple lines to make checkstyle happy. But spotless merges these lines into one line. it voilates checkstyle again.

**Comment by yanghua** [comment]
> For example, a line contains 119 chars. I split it into multiple lines to make checkstyle happy. But spotless merges these lines into one line. it voilates checkstyle again.

Oh... interesting, Can you share your case?

**Comment by yanghua** [comment]
Let me be clear, did you suggest only removing the line length rule:

```
<module name="LineLength">
        <property name="max" value="100"/>
        <property name="ignorePattern" value="^package.*|^import.*|a href|href|http://|https://|ftp://"/>
    </module>
```

Or the whole file: `checkstyle.xml`?

**Comment by chenkovsky** [comment]
removing this rule works for me. 😄

**Pull request merged**
