### PR TITLE
feat(rust): add support for loongarch

### PR DESCRIPTION
**Pull request by heiher**
This PR adds support for [loongarch](https://doc.rust-lang.org/rustc/platform-support/loongarch-linux.html) target.

### CODE REVIEW

**Comment by eddyxu** [comment]
Thanks @heiher, this is super interesting. Curious how should we test loongarch in CI?
Can we use KVM in Github action?

**Comment by wjones127** [comment]
Thanks for the contribution.

To be honest, I'm on the fence on whether we want to add CI checks for this. On one hand I usually wouldn't want to merge support for something that doesn't have some validation in CI. On the other hand, this is the first time I've heard of this platform, so I'm not sure it's worth the CI spend to do so. (If we did add it, should we also add PowerPC, aarch64 Windows, riscv64gc, and so on? This could quickly add up to a lot of jobs.) I think if we did do CI checks, I'd be inclined to make them nightly at most frequent.

**Comment by heiher** [comment]
Thanks. Can we skip CI for LoongArch? [Debian loong64 port](https://wiki.debian.org/Ports/loong64) is still in progress, and there is no particularly suitable open source upstream community distribution for CI.

**Review by wjones127 — APPROVED** [review]
I'm okay merging this for now. But we make no promises that we won't break it later, since we aren't testing it in CI. You are welcome to make future PRs with fixes.

**Comment by heiher** [comment]
> I'm okay merging this for now. But we make no promises that we won't break it later, since we aren't testing it in CI. You are welcome to make future PRs with fixes.

Okay. Thanks.

**Pull request merged**
