### PR TITLE
chore: add ruff copyright check

### PR DESCRIPTION
**Pull request by eddyxu**
Add a ruff rule to enforce copyright header is presented in python files

### CODE REVIEW

**Review by wjones127 — APPROVED** [review]
🙌

**Comment by wjones127** [comment]
Looks like the mirror failed when installing system deps. Should be able to just retry the job?

**Comment by eddyxu** [comment]
> Looks like the mirror failed when installing system deps. Should be able to just retry the job?

Lemme take a look. seems that protobuf is not installed.

**Comment by wjones127** [comment]
@eddyxu It's just that it failed here:

https://github.com/lancedb/lance/actions/runs/7200989635/job/19616217571?pr=1716#step:5:313

The install command is here: https://github.com/lancedb/lance/blob/c65afc89cd3725be3317bf0c169e699dadcc5e77/.github/workflows/build_linux_wheel/action.yml#L33-L37

**Pull request merged**
