### PR TITLE
feat: support merge fragment with dataset

### PR DESCRIPTION
**Pull request by chenkovsky**
this PR allows merge dataset concurrently.

### CODE REVIEW

**Review by westonpace — COMMENTED** [review]
What is the goal of the PR?  Normally when distributing work across fragments we are trying to divide N units of work into F tasks where each task does N/F units of work.

However, with this merge we are taking N units of work (read N rows, build hashtable of size N, write N rows) and breaking into F tasks where each task is still (more or less) N units of work (read N rows, build hashtable of size N, write N/F rows).

Is the problem just that the write step is very expensive?

**Comment by chenkovsky** [comment]
@westonpace . for example, I have tagged all rows, tag is created by a cluster algorithm. so it's hard to use add_columns api to create this column. so I want to shuffle the tag dataframe based on fragment_id
for example dataframe schema is <row_addr,tag>, we can get fragment_id from row_addr, then for each fragment, we only need to build a small piece of hashtable, and merge quickly.

**Comment by westonpace** [comment]
I see.  I had misunderstood.  I thought the hashtable was built on the DS for some reason.  However, you are right, on closer look we are making the hashtable on the fragment data so it's only the scan step that remains N units of work.

Also, perhaps more importantly, this reduces the amount of memory required because we have a smaller hashtable.

**Review by wjones127 — APPROVED** [review]
Looks good. Thanks for working on this

**Pull request merged**
