### PR TITLE
chore(java): enable separate java builds

### PR DESCRIPTION
**Pull request by LuQQiu**
The java build with full java 8 / 11 / 17 compile and tests takes a long time.
This PR separate the builds so that they can be paralleled

### CODE REVIEW

**Comment by QianZhu** [comment]
Do we need 3 yaml files? Or we can just use one template and pass the Java versions in? This can be taken care of later, if you feel appropriate.

**Review by QianZhu — APPROVED** [review]

**Review by eddyxu — CHANGES_REQUESTED** [review]
Can we use github action metric to setup java version?

**Comment by LuQQiu** [comment]
@eddyxu @QianZhu PTAL, thanks

**Comment by LuQQiu** [comment]
@eddyxu PTAL, thanks

**Review by eddyxu — APPROVED** [review]

**Pull request merged**
